### ISSUE TITLE
Only answer to tagged messages.

### ISSUE THREAD

**Issue by FooleanBool** [jake83741/vnc-lm#1]
Tried about five different bots, but this was the first one I could get to join a channel!
Would be great if the bot could be configured to only listen to tagged messages on a server-by-server basis.
Thanks for your efforts.

**Comment by jake83741** [comment]
Hi, glad it worked for you! I made the change you requested. Now, the .env.example has the following fields.
```
# Channels (or threads) where the bot is allowed to respond. Format like this ChannelID1,ChannelId2,ThreadID1. Defaults to responding everywhere.
ALLOWED_CHANNELS=
# Require tagging the bot to get a response. Set to either true or false. Defaults to false.
REQUIRE_MENTION=
```

Let me know if there's any more issues. Thanks!

**Comment by jake83741** [comment]
Hi, glad to hear it worked for you!

I added a field to the `.env` to require mention. It's off by default. 

```
# Require the bot to be mentioned or not. Defaults to false
REQUIRE_MENTION=
```

It's working well for me. Let me know if you have any issues with it. Thanks!

**Comment by FooleanBool** [comment]
I know this is closed now, but I wanted to thank you for working so quickly on my suggestion.
I realised afterwards that discord itself can control the channels, so only the parameter to respond to tag or not was needed.
I will try the new files as soon as I get chance.
