### ISSUE TITLE
Prompt definition?

### ISSUE THREAD

**Issue by Darkhub** [jake83741/vnc-lm#3]
I am using AnythingLLM to interact with ollama and in model configuration there is an option for entering a Prompt containing context and instructions to pass to IA for changing responses behaviour.
For example the default prompt is:
"Given the following conversation, relevant context, and a follow up question, reply with an answer to the current question the user is asking. Return only your response to the question given the above information following the users instructions as needed."

Would it be possible to include this functionality in bot?
I think this would be a really interesting feature since using Prompt it is possible to modify AI personality for example.

Thanks for your work.

**Comment by jake83741** [comment]
Hi, If I'm understanding correctly, I think you can do that with the system_parameter in `/model`.
