### ISSUE TITLE
im getting an error when trying to use the bot:

### ISSUE THREAD

**Issue by kroryan** [jake83741/vnc-lm#4]
so im getting an error when i try to run the bot i will attach an image, the file .env should be rigth i know the token and the other info is right it works with other bot, here the image:

![image](https://github.com/user-attachments/assets/b0fc9e79-d958-4000-a640-e535cc2e1c44)

**Comment by jake83741** [comment]
Is your node.js up to date? [I found this issue that seems to be similar](https://github.com/Androz2091/discord-giveaways/issues/368#issuecomment-915533482). I was unable to recreate the issue on my end, I tried the docker installation and the manual installation, everything worked for me. My node version is 20.9.0.

**Comment by jake83741** [comment]
Ok, let me know if updating node.js fixes the error. Good luck!

**Comment by kroryan** [comment]
> Ok, please let me know if updating node.js fixes the error. Good luck!

hey mate it works i updated to 20.17 or something like that and its running now, thanks so much man

**Comment by jake83741** [comment]
> > Ok, please let me know if updating node.js fixes the error. Good luck!
> 
> hey mate it works i updated to 20.17 or something like that and its running now, thanks so much man
> 
> ![image](https://private-user-images.githubusercontent.com/69607760/369532204-60fc8e1c-1b4e-4b96-b2f3-406740ed93bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NjM4NjAsIm5iZiI6MTcyNjg2MzU2MCwicGF0aCI6Ii82OTYwNzc2MC8zNjk1MzIyMDQtNjBmYzhlMWMtMWI0ZS00Yjk2LWIyZjMtNDA2NzQwZWQ5M2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDIwMTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNzEwZTg0ZTYxNTRhMTQyYzljN2Y3M2QyZTcxYWFlNTcwZGZjNzg1NDEwMWQxYjg2YWM5YThmOGViZGY1ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p7LOl3zII_YWZFYYt789F2xM8KGA19FFlnU6WNGTe3k)
> 
> this didnt solve only this problem for me i was having similar issues with other bots, thanks man

Awesome, glad to hear it works!
