### ISSUE TITLE
Bedrock Runtime Provider Integration. 

### ISSUE THREAD

**Issue by tavikano** [jake83741/vnc-lm#5]
Hello jake83741,

Love the project, currently iterating over it AWS's bedrock integration. Let me know if this is in the roadmap and once ready I could submit a PR or we can pair program to implement. 

Regards, 

- Octavio Cano

**Comment by jake83741** [comment]
Hi Octavio, 

I'm very happy to hear you enjoy the project! I don't have any plans to support for AWS Bedrock. I'm really just focusing on APIs with free tiers. Feel free to fork the project though and add it. 

Thanks,

Jake

**Comment by jake83741** [comment]
Hi Octavio,

I just wanted to follow up on this. I'm working on adding support for LiteLLM and noticed it includes support for Amazon Bedrock. I'll probably be pushing the update some time in the next couple days.

**Comment by tavikano** [comment]
Excellent, I have used LiteLLM with Bedrock previously so looking forward to the Feature. Let me know if you have encounter any AWS related issues. Thanks!

**Comment by jake83741** [comment]
> Excellent, I have used LiteLLM with Bedrock previously so looking forward to the Feature. Let me know if you have encounter any AWS related issues. Thanks!

Just added the code! Let me know if there's any issues. I don't have AWS so I couldn't test Bedrock but I tried a couple different providers and it seemed to be working.

**Comment by tavikano** [comment]
Will test ASAP and let you know!

**Comment by tavikano** [comment]
created PR: https://github.com/jake83741/vnc-lm/pull/6

**Comment by tavikano** [comment]
So streaming is still pending due, for some reason Llama stopped streaming(i suspect rate limit changes due to inference profiles. 

So far Claude and Lllama 3.2 are working pretty good.

**Comment by tavikano** [comment]
Issue revolved.
